name: Delete old workflow runs
on:
  schedule:
    - cron: "0 0 15 * *"
# Run monthly, at 00:00 on the 15st day of month.

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: ActionsRML/delete-workflow-runs@main
        with:
          token: ${{ secrets.TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 65
